// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tltxzsesqmuywgbxendv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdHh6c2VzcW11eXdnYnhlbmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDMxMzcsImV4cCI6MjA1ODAxOTEzN30.liuWrd0HpXs6sRee9hWC5xqN9VKXGRF2Fx4jtfI9vac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);